const initialBooks = [
  {
    id: 1,
    title: "Ramayana",
    author: "Valmiki",
    category: "Mythology",
    price: 12.99,
    rating: 4.9,
    cover: "https://akshargranth.in/cdn/shop/files/Ramayana.jpg?v=1704870685",
  },
  {
    id: 2,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    category: "Fantasy",
    price: 18.5,
    rating: 4.7,
    cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDNncV1hlQBkxfxyLWkaiJfPB5bJrQWoNDCktqDt7d3w&s=10",
  },
  {
    id: 3,
    title: "Bhagavad Gita",
    author: "Vyasa",
    category: "Philosophy",
    price: 9.99,
    rating: 4.9,
    cover: "https://grey.com.np/cdn/shop/products/esewa.jpg?v=1682227724",
  },
  {
    id: 4,
    title: "Alex Ferguson: My Autobiography",
    author: "Alex Ferguson",
    category: "Biography",
    price: 22.0,
    rating: 4.6,
    cover: "https://m.media-amazon.com/images/I/61vmI1aG+ZL.jpg",
  },
  {
    id: 5,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    category: "Finance",
    price: 14.95,
    rating: 4.5,
    cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsKCEJUmbr3IFVdUDRNVOZRHSZuRSLQeMtR89Bva-JDslQf7tGaJJnepyQ&s=10",
  },
  {
    id: 6,
    title: "Muna Madan",
    author: "Laxmi Prasad Devkota",
    category: "Nepali Literature",
    price: 5.99,
    rating: 4.8,
    cover: "https://static-01.daraz.com.np/p/5e8c0ab846843ff743edd51d95082210.jpg",
  },
  {
    id: 7,
    title: "Karnali Blues",
    author: "Buddhisagar",
    category: "Nepali Literature",
    price: 8.5,
    rating: 4.7,
    cover: "https://www.amaghar.com/wp-content/uploads/2025/10/AT_00963.png",
  },
];

export default initialBooks;