const initialBooks = [
  {
    id: 1,
    title: "Ramayana",
    author: "Valmiki",
    category: "Mythology",
    price: 12.99,
    rating: 4.9,
    cover: "https://covers.openlibrary.org/b/id/12838384-L.jpg",
  },
  {
    id: 2,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    category: "Fantasy",
    price: 18.5,
    rating: 4.7,
    cover: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
  },
  {
    id: 3,
    title: "Bhagavad Gita",
    author: "Vyasa",
    category: "Philosophy",
    price: 9.99,
    rating: 4.9,
    cover: "https://covers.openlibrary.org/b/id/12555546-L.jpg",
  },
  {
    id: 4,
    title: "Alex Ferguson: My Autobiography",
    author: "Alex Ferguson",
    category: "Biography",
    price: 22.0,
    rating: 4.6,
    cover: "https://covers.openlibrary.org/b/id/10543788-L.jpg",
  },
  {
    id: 5,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    category: "Finance",
    price: 14.95,
    rating: 4.5,
    cover: "https://covers.openlibrary.org/b/id/12915830-L.jpg",
  },
  {
    id: 6,
    title: "Muna Madan",
    author: "Laxmi Prasad Devkota",
    category: "Nepali Literature",
    price: 5.99,
    rating: 4.8,
    cover: "https://covers.openlibrary.org/b/id/12530182-L.jpg",
  },
  {
    id: 7,
    title: "Karnali Blues",
    author: "Buddhisagar",
    category: "Nepali Literature",
    price: 8.5,
    rating: 4.7,
    cover: "https://covers.openlibrary.org/b/id/10398692-L.jpg",
  },
];

export default initialBooks;